import { Poppins } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider
} from '@clerk/nextjs'
import Navbar from '@/components/navbar';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
      <body
        className={`${poppins.variable} font-sans antialiased`}
        >
        <Navbar />
        {children}
      </body>
        </ClerkProvider>
    </html>
  );
}
